name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: ".nvmrc"
      - run: yarn install
      - run: yarn build
      - run: yarn test --passWithNoTests
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/index.js

  integration:
    needs: build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist # overwrite dist/index.js
      - uses: ./
